pipeline{
    agent any
    stages{
        stage('file creation'){
            steps{
                echo 'touch a1'
            }
        }
        stage('inputting into file'){
            steps{
                echo 'touch a2'
            }
        }
        stage('permissions of file'){
            steps{
                echo 'chmod 777 a1'
            }
        }
        stage('file excccreation'){
            steps{
                echo 'touch b1'
            }
        }




    }

}
