pipeline{
    agent any
    stages{
        stage('file creation'){
            steps{
                sh''' cat /etc/os-release  '''
            }
        }
        stage('memory details'){
            steps{
                sh''' free -mh  '''
            }
        }
        stage('creation of file'){
            steps{
                sh''' touch a1  '''
            }
        }
        stage('changing permissions of a file'){
            steps{
                sh''' chmod 777 a1  '''
            }
        }




    }

}
